### ISSUE TITLE
ArgumentOutOfRangeException in Replicator.FilterTransaction / TransactionLog.LogApplicator.Apply

### ISSUE THREAD

**Issue by per-samuelsson** [StarcounterPrefabs/LogStreamer#12]
I have one replicating root database ("harbor") and I'm starting a child of that ("regina"). Both databases run in latest **pnext** nightly (Version=2.3.588). The latest replication repo commit: https://github.com/Starcounter/Replicator/commit/3ebd7f5b61184d568d6e4c542c2f16c3cb4da959.

Both databases run the same suite of applications. Replication enabled: all tables.

Starting "harbor" works. When I'm starting "regina", I experience this:

```
Launcher -> regina (started, default port 8080, admin 8181)                                                             
SignIn -> regina (started, default port 8080, admin 8181)
Replicator -> regina (started, default port 8080, admin 8181)                                                           
PIM -> regina (starting application ...)

Replicator: c183507f-c32d-4051-813f-1906dca3a016: 
FilterTransaction 
Starcounter.TransactionLog.LogPosition: System.ArgumentOutOfRangeException: 
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at Replicator.Replicator.FilterTransaction(LogReadResult lrr) in C:\Users\Per\Git\SweOffshore\SweOffshoreReplicator\Replicator.cs:line 410
Replicator: "RPu532  TI"Sweoffshore.Generic.PartOf" r30000000019 C"Superset" r30000000017  C"Subset" r30000000018   I"Sweoffshore.ProductInformationManagement.ProductType" r30000000018 C"Name" "Food"  C"IsEnabled" u1  C"IsRootNode" u1   I"Sweoffshore.ProductInformationManagement.ProductType" r30000000017 C"Name" "Product"  C"IsEnabled" u1   I"Sweoffshore.Generic.AssociatedWith" r30000000016 C"Somebody" r30000000012  C"Something" r30000000014   I"Sweoffshore.Generic.AssociatedWith" r30000000015 C"Somebody" r30000000012  C"Something" r30000000013   I"Sweoffshore.Location.Ship" r30000000014 C"Name" "Regina Baltica MS"   I"Sweoffshore.Location.Ship" r30000000013 C"Name" "Patria Seaways MS"   I"Sweoffshore.Owner.Company" r30000000012 C"Name" "SweOffshore Maritime AB"  C"Address" r30000000010   I"Sweoffshore.Owner.Company" r30000000011 C"Name" "Nord Marine Ltd."  C"Address" r30000000009   I"Simplified.Ring3.Address" r30000000010 C"Name" "SE-41103, Sweden, Gothenburg, Odinsgatan, 11"  C"_Street" "Odinsgatan"  C"_House" "11"  C"_PostalCode" "SE-41103"  C"_City" "Gothenburg"  C"_Country" "Sweden"   I"Simplified.Ring3.Address" r30000000009 C"Name" "LV-1045, Latvia, Riga, KaÄ·asÄ"kÄ¼a dambis, 31"  C"_Street" "KaÄ·asÄ"kÄ¼a dambis"  C"_House" "31"  C"_PostalCode" "LV-1045"  C"_City" "Riga"  C"_Country" "Latvia"     ": Starcounter.DbException: ScErrTableNotFound (SCERR4230): Table with specified name not found.
Version: 2.3.588.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4230.
   at Starcounter.TransactionLog.LogApplicator.Apply(TransactionData transaction_data) in C:\TeamCity\TeamCity9\buildAgent\work\sc-38\Level1\src\Server\Starcounter.TransactionLog\LogApplicator.cs:line 16
   at Replicator.Replicator.<>c__DisplayClass57_0.<ProcessStringMessage>b__0() in C:\Users\Per\Git\SweOffshore\SweOffshoreReplicator\Replicator.cs:line 511
   at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in C:\TeamCity\TeamCity9\buildAgent\work\sc-38\Level1\src\Starcounter\Db.cs:line 300
   at Replicator.Replicator.ProcessStringMessage(String message) in C:\Users\Per\Git\SweOffshore\SweOffshoreReplicator\Replicator.cs:line 493
Replicator: c183507f-c32d-4051-813f-1906dca3a016 disconnected
Replicator: c183507f-c32d-4051-813f-1906dca3a016 disconnected
ReplicationChild.Reconnect: "ws://localhost:8082/Replicator/service": Exception System.AggregateException: One or more errors occurred. ---> System.Net.WebSockets.WebSocketException: The WebSocket is in an invalid state ('CloseReceived') for this operation. Valid states are: 'Open, CloseSent'
   at System.Net.WebSockets.WebSocket.ThrowOnInvalidState(WebSocketState state, WebSocketState[] validStates)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('CloseReceived') for this operation. Valid states are: 'Open, CloseSent'
   at System.Net.WebSockets.WebSocket.ThrowOnInvalidState(WebSocketState state, WebSocketState[] validStates)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()<---

Replicator: "RPu533  TI"Simplified.Ring3.AddressRelationType" r30000000042 C"Name" "Current Location"   I"Simplified.Ring3.AddressRelation" r30000000041 C"WhatIs" r30000000014  C"ToWhat" r30000000024  C"ContactInfoRelationType" r30000000042   I"Simplified.Ring3.AddressRelationType" r30000000040 C"Name" "Current Location"   I"Simplified.Ring3.AddressRelation" r30000000039 C"WhatIs" r30000000014  C"ToWhat" r30000000025  C"ContactInfoRelationType" r30000000040   I"Simplified.Ring3.AddressRelationType" r30000000038 C"Name" "Current Location"   I"Simplified.Ring3.AddressRelation" r30000000037 C"WhatIs" r30000000014  C"ToWhat" r30000000023  C"ContactInfoRelationType" r30000000038   I"Simplified.Ring3.SystemUserGroupMember" r30000000036 C"WhatIs" r30000000033  C"ToWhat" r30000000022   I"Simplified.Ring3.SystemUserGroupMember" r30000000035 C"WhatIs" r30000000032  C"ToWhat" r30000000021   I"Simplified.Ring3.SystemUserGroupMember" r30000000034 C"WhatIs" r30000000031  C"ToWhat" r30000000020   I"Simplified.Ring3.SystemUser" r30000000033 C"Name" "user"  C"WhatIs" r30000000025  C"Password" "/a6OfLliG2IpRy9z3AQNmITtFFMCpnvDVXPjB9/cIeY="  C"PasswordSalt" "urray4QJbKXFnL0OZ5fjWg=="   I"Simplified.Ring3.SystemUser" r30000000032 C"Name" "fboss"  C"WhatIs" r30000000024  C"Password" "tvHdKjX1IL+lHXn12W3O74/VZlbP2yNwHNnDzZhAlxo="  C"PasswordSalt" "PFGjqZmqDARDAs9nGmFopg=="   I"Simplified.Ring3.SystemUser" r30000000031 C"Name" "admin"  C"WhatIs" r30000000023  C"Password" "Lba8EYl0AozdZJzDUHILQZMqbw7qbGGJ/HQfdMoxCcI="  C"PasswordSalt" "vTPHKWhzEaPQnqSTYV+zQg=="   I"Sweoffshore.Location.Place" r30000000030 C"Name" "Riga"   I"Simplified.Ring3.AddressRelationType" r30000000029 C"Name" "Current Location"   I"Simplified.Ring3.AddressRelation" r30000000028 C"WhatIs" r30000000030  C"ToWhat" r30000000024  C"ContactInfoRelationType" r30000000029   I"Simplified.Ring3.AddressRelationType" r30000000027 C"Name" "Current Location"   I"Simplified.Ring3.AddressRelation" r30000000026 C"WhatIs" r30000000014  C"ToWhat" r30000000025  C"ContactInfoRelationType" r30000000027   I"Simplified.Ring2.Person" r30000000025 C"Name" "Storage Manager"  C"_FirstName" "Storage"  C"_LastName" "Manager"   I"Simplified.Ring2.Person" r30000000024 C"Name" "Food Boss"  C"_FirstName" "Food"  C"_LastName" "Boss"   I"Simplified.Ring2.Person" r30000000023 C"Name" "Jens Willmer"  C"_FirstName" "Jens"  C"_LastName" "Willmer"   I"Simplified.Ring3.SystemUserGroup" r30000000022 C"Name" "Storage Manager"  C"Parent" r30000000021   I"Simplified.Ring3.SystemUserGroup" r30000000021 C"Name" "Storage Administrator"  C"Parent" r30000000020   I"Simplified.Ring3.SystemUserGroup" r30000000020 C"Name" "Administrator"     ": Starcounter.DbException: ScErrTableNotFound (SCERR4230): Table with specified name not found.
Version: 2.3.588.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4230.
   at Starcounter.TransactionLog.LogApplicator.Apply(TransactionData transaction_data) in C:\TeamCity\TeamCity9\buildAgent\work\sc-38\Level1\src\Server\Starcounter.TransactionLog\LogApplicator.cs:line 16
   at Replicator.Replicator.<>c__DisplayClass57_0.<ProcessStringMessage>b__0() in C:\Users\Per\Git\SweOffshore\SweOffshoreReplicator\Replicator.cs:line 511
   at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in C:\TeamCity\TeamCity9\buildAgent\work\sc-38\Level1\src\Starcounter\Db.cs:line 300
   at Replicator.Replicator.ProcessStringMessage(String message) in C:\Users\Per\Git\SweOffshore\SweOffshoreReplicator\Replicator.cs:line 493
Replicator: 00000000-0000-0000-0000-000000000000: FilterTransaction Starcounter.TransactionLog.LogPosition: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at Replicator.Replicator.FilterTransaction(LogReadResult lrr) in C:\Users\Per\Git\SweOffshore\SweOffshoreReplicator\Replicator.cs:line 410
Replicator: 00000000-0000-0000-0000-000000000000: FilterTransaction Starcounter.TransactionLog.LogPosition: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at Replicator.Replicator.FilterTransaction(LogReadResult lrr) in C:\Users\Per\Git\SweOffshore\SweOffshoreReplicator\Replicator.cs:line 410

[09:47:48, Starcounter (regina)]
System.ArgumentException: The close status description 'Starcounter.DbException: ScErrTableNotFound (SCERR4230): Table with specified name not found.
Version: 2.3.588.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4230.
   at Starcounter.TransactionLog.LogApplicator.Apply(TransactionData transaction_data) in C:\TeamCity\TeamCity9\buildAgent\work\sc-38\Level1\src\Server\Starcounter.TransactionLog\LogApplicator.cs:line 16
   at Replicator.Replicator.<>c__DisplayClass57_0.<ProcessStringMessage>b__0() in C:\Users\Per\Git\SweOffshore\SweOffshoreReplicator\Replicator.cs:line 511
   at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in C:\TeamCity\TeamCity9\buildAgent\work\sc-38\Level1\src\Starcounter\Db.cs:line 300
   at Replicator.Replicator.ProcessStringMessage(String message) in C:\Users\Per\Git\SweOffshore\SweOffshoreReplicator\Replicator.cs:line 493' is too long. The UTF8-representation of the status description must not be longer than 123 bytes.
Parameter name: statusDescription
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\TeamCity9\buildAgent\work\sc-38\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 132
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity9\buildAgent\work\sc-38\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 86
ParamName=statusDescription
HResult=-2147024809
```

Look to me like there is a chain of errors here. Starting with `ScErrTableNotFound` in `TransactionLog.LogApplicator.Apply` and not sufficiently handled in some higher level.

**Comment by per-samuelsson** [comment]
@bigwad @linkdata

**Comment by linkdata** [comment]
Old copy-paste bug.

Check the code (Replicator.cs, line 410). The remove is from `creates`, but should be from `updates`.
`tran.creates.RemoveAt(index);` should be `tran.updates.RemoveAt(index);`. Same error a few lines down, also removing from the `creates` instead of `updates`.

**Comment by linkdata** [comment]
Btw, don't fix this in this repo, as I have way to large a changeset pending on these files. Just fix it in your fork.

**Comment by per-samuelsson** [comment]
Thanks @linkdata.

> Just fix it in your fork.

I actually think I will not address this at all right now, since I want to hear whats up with the underlying table not found thingy first, considering its even logged as critical errors by means of a slipping exception from `TransactionLog.LogApplicator.Apply`.

**Comment by linkdata** [comment]
TableNotFound might indicate that you're not running the same set of applications on all involved databases. If they are running (and are the same version), it's a bit more weird. Can you find out which table it's faulting on?

**Comment by per-samuelsson** [comment]
> TableNotFound might indicate that you're not running the same set of applications on all involved databases.

I suspected that, but thats not the case: I'm running the exact same set of executables in both databases.

> Can you find out which table it's faulting on?

I would have hoped that would be part of the error message. To me, it seems a bit awkward raising an error saying that a table / file / whatever is not find, and include no hint to *what* artifact is missing. But maybe that's just me.

**Comment by linkdata** [comment]
> To me, it seems a bit awkward raising an error saying that a table / file / whatever is not find, and include no hint to what artifact is missing. But maybe that's just me.

No, it's not just you. But [that's a](https://github.com/Starcounter/Starcounter/issues/2629) separate [issue](https://github.com/Starcounter/Starcounter/issues/3138). And probably others if I search harder.

**Comment by per-samuelsson** [comment]
With the latest replicator bits and a totally fresh environment, the index out of range from the OP no longer occur, but the underlying failure is. Replicator commit in use: https://github.com/Starcounter/Replicator/commit/46c2bcf68883adc9f32486faadf08f000e1d60ed (from @linkdata).

It seem deterministic, if I recreate the environment from scratch every time. So I'll try again doing so, and see if I can debug the replicator and see if the exception from the underlying log gives any clue runtime.

**Comment by linkdata** [comment]
Run it with Fiddler active so you can see the sequence of replication operations that occur. May be a clue in there.

**Comment by per-samuelsson** [comment]
Hmm, I noticed a nuance of the error now I didn't see before:

```
System.ArgumentException: The close status description 'Starcounter.DbException: ScErrTableNotFound (SCERR4230): Table with specified name not found.
Version: 2.3.588.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4230.
   at Starcounter.TransactionLog.LogApplicator.Apply(TransactionData transaction_data) in C:\TeamCity\TeamCity9\buildAgent\work\sc-38\Level1\src\Server\Starcounter.TransactionLog\LogApplicator.cs:line 16
   at Replicator.Replicator.<>c__DisplayClass69_0.<ProcessStringMessage>b__0() in C:\Users\Per\Git\SweOffshore\SweOffshoreReplicator\Replicator.cs:line 510
   at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in C:\TeamCity\TeamCity9\buildAgent\work\sc-38\Level1\src\Starcounter\Db.cs:line 300
   at Replicator.Replicator.ProcessStringMessage(String message) in C:\Users\Per\Git\SweOffshore\SweOffshoreReplicator\Replicator.cs:line 494' is too long. The UTF8-representation of the status description must not be longer than 123 bytes.
Parameter name: statusDescription
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\TeamCity9\buildAgent\work\sc-38\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 132
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity9\buildAgent\work\sc-38\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 86
ParamName=statusDescription
HResult=-2147024809
```

It seems the message is **"The close status description `[placeholder]`  is too long. The UTF8-representation of the status description must not be longer than 123 bytes"**.

And that the placeholder given is the error+stack trace:

```
Starcounter.DbException: ScErrTableNotFound (SCERR4230): Table with specified name not found.
Version: 2.3.588.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4230.
   at Starcounter.TransactionLog.LogApplicator.Apply(TransactionData transaction_data) in C:\TeamCity\TeamCity9\buildAgent\work\sc-38\Level1\src\Server\Starcounter.TransactionLog\LogApplicator.cs:line 16
   at Replicator.Replicator.<>c__DisplayClass69_0.<ProcessStringMessage>b__0() in C:\Users\Per\Git\SweOffshore\SweOffshoreReplicator\Replicator.cs:line 510
   at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in C:\TeamCity\TeamCity9\buildAgent\work\sc-38\Level1\src\Starcounter\Db.cs:line 300
   at Replicator.Replicator.ProcessStringMessage(String message) in C:\Users\Per\Git\SweOffshore\SweOffshoreReplicator\Replicator.cs:line 494
```

**Comment by per-samuelsson** [comment]
> Run it with Fiddler active so you can see the sequence of replication operations that occur. May be a clue in there.

Yeah, I'll try something like that I guess, but everything takes so much time since I have to recreate the whole setup from scratch every time to get this bastard appearing. :roller_coaster:

**Comment by linkdata** [comment]
Reasonably, one of the tables being inserted to/updated doesn't exist. The table names are the ones following an `I`, `U` or `D`, as in `I"Sweoffshore.Location.Place"`. Also, check that `Replicator.Replication` exists, which is the only table not named in the text that is being accessed.

**Comment by linkdata** [comment]
@bigwad Alternatively, possibly this is related to mapping? Is the `Simplified.RingX.Stuff` tables handled specially and not recognized by the kernel?

**Comment by bigwad** [comment]
I'm not aware of any special processing

**Comment by per-samuelsson** [comment]
@linkdata 

I was able to attach a debugger and manually grab the failing transaction. It contains 11 inserts, of various tables, manually extracted one by one in the Immediate Window (programming for dummies!) :dancer: 

```
tran.transaction_data.creates
Count = 11
    [0]: {Starcounter.TransactionLog.create_record_entry}
    [1]: {Starcounter.TransactionLog.create_record_entry}
    [2]: {Starcounter.TransactionLog.create_record_entry}
    [3]: {Starcounter.TransactionLog.create_record_entry}
    [4]: {Starcounter.TransactionLog.create_record_entry}
    [5]: {Starcounter.TransactionLog.create_record_entry}
    [6]: {Starcounter.TransactionLog.create_record_entry}
    [7]: {Starcounter.TransactionLog.create_record_entry}
    [8]: {Starcounter.TransactionLog.create_record_entry}
    [9]: {Starcounter.TransactionLog.create_record_entry}
    [10]: {Starcounter.TransactionLog.create_record_entry}
tran.transaction_data.creates[0]
{Starcounter.TransactionLog.create_record_entry}
    columns: {Starcounter.TransactionLog.column_update[2]}
    key: {Starcounter.TransactionLog.reference}
    table: "Sweoffshore.Generic.PartOf"
tran.transaction_data.creates[1]
{Starcounter.TransactionLog.create_record_entry}
    columns: {Starcounter.TransactionLog.column_update[3]}
    key: {Starcounter.TransactionLog.reference}
    table: "Sweoffshore.ProductInformationManagement.ProductType"
tran.transaction_data.creates[2]
{Starcounter.TransactionLog.create_record_entry}
    columns: {Starcounter.TransactionLog.column_update[2]}
    key: {Starcounter.TransactionLog.reference}
    table: "Sweoffshore.ProductInformationManagement.ProductType"
tran.transaction_data.creates[3]
{Starcounter.TransactionLog.create_record_entry}
    columns: {Starcounter.TransactionLog.column_update[2]}
    key: {Starcounter.TransactionLog.reference}
    table: "Sweoffshore.Generic.AssociatedWith"
tran.transaction_data.creates[4]
{Starcounter.TransactionLog.create_record_entry}
    columns: {Starcounter.TransactionLog.column_update[2]}
    key: {Starcounter.TransactionLog.reference}
    table: "Sweoffshore.Generic.AssociatedWith"
tran.transaction_data.creates[5]
{Starcounter.TransactionLog.create_record_entry}
    columns: {Starcounter.TransactionLog.column_update[1]}
    key: {Starcounter.TransactionLog.reference}
    table: "Sweoffshore.Location.Ship"
tran.transaction_data.creates[6]
{Starcounter.TransactionLog.create_record_entry}
    columns: {Starcounter.TransactionLog.column_update[1]}
    key: {Starcounter.TransactionLog.reference}
    table: "Sweoffshore.Location.Ship"
tran.transaction_data.creates[7]
{Starcounter.TransactionLog.create_record_entry}
    columns: {Starcounter.TransactionLog.column_update[2]}
    key: {Starcounter.TransactionLog.reference}
    table: "Sweoffshore.Owner.Company"
tran.transaction_data.creates[8]
{Starcounter.TransactionLog.create_record_entry}
    columns: {Starcounter.TransactionLog.column_update[2]}
    key: {Starcounter.TransactionLog.reference}
    table: "Sweoffshore.Owner.Company"
tran.transaction_data.creates[9]
{Starcounter.TransactionLog.create_record_entry}
    columns: {Starcounter.TransactionLog.column_update[6]}
    key: {Starcounter.TransactionLog.reference}
    table: "Simplified.Ring3.Address"
tran.transaction_data.creates[10]
{Starcounter.TransactionLog.create_record_entry}
    columns: {Starcounter.TransactionLog.column_update[6]}
    key: {Starcounter.TransactionLog.reference}
    table: "Simplified.Ring3.Address"
```

From that I still can't pinpoint the one it is, obv. But just looking at it, I just realized something: could it be so that the log is not "low level" enough to manipulate data without user code being loaded, and that I have started applications in the wrong order? If so, we really need to add to the documentation how important it is to start the replicator **last** in the app suite test.

**Comment by linkdata** [comment]
All classes being replicated must be loaded before starting replication, but the Replicator itself won't start doing things until it's told to, so starting order should not matter. Or am I misunderstanding you?

**Comment by linkdata** [comment]
Ah, hold on. You mean when it's *receiving*, in which case yes, if it gets contacted by a peer before all user classes are loaded there will be problems. Not sure how an app would check that though. Or if it even should be able to. Easy mode test for it. See if waiting a bit (letting all apps spin up) before starting replication makes the problem go away.

Again, start order should not matter, only that all usercode is loaded before starting replication.

**Comment by per-samuelsson** [comment]
> Or am I misunderstanding you?

Not at all.

> All classes being replicated must be loaded before starting replication, but the Replicator itself won't start doing things until it's told to, so starting order should not matter.

Starting order will matter if you start it with the "enabled" switch, that I do. And that I think will be quite a normal setup. The strategy is probably fine, I just didn't see anywhere that was a requisite, so we should probably remember do document / highlight it and/or improve the error message.

**Comment by per-samuelsson** [comment]
> You mean when it's *receiving*, in which case yes, if it gets contacted by a peer before all user classes are loaded there will be problems.

Spot on. It's not acute now that I know about it, but we probably must come up with something like I wrote above.

**Comment by linkdata** [comment]
Yeah. Technically, this is no different from stopping user apps on the receiving side while replication is in process, or starting new apps on sender side that aren't running on receiver. Exact same thing will happen.

Possible workaround would be to catch SCERR4230 and restart the replication session, hoping that the usercode will come online soon. Not a good solution since it can hide actual misconfiguration issues, but since SCERR4230 doesn't report the name of the problematic table, it's not much use for fixing misconfiguration anyway.

**Comment by per-samuelsson** [comment]
>   Technically, this is no different from stopping user apps on the receiving side while replication is in process, or starting new apps on sender side that aren't running on receiver.

Exactly. Good catch. 

I don't think we should rush the solution as in "we need to solve this today", but we should be aware of it and write it somewhere, and then try to come up with something practical. I can start giving it some thought too, and then lets sync our thinking around it like later this week or so.

**Comment by bigwad** [comment]
Actually, requirements are more relaxed. It's enough for database class to be registered within metadata. We may play with this difference. Say, register classes once application is installed and not wait it to be started.

**Comment by per-samuelsson** [comment]
> Actually, requirements are more relaxed. It's enough for database class to be registered within metadata. 

I see. That's something new in **pnext** then I think.

Then maybe the simple thing would be to just either self-disable or even unload/stop the replicator once it catch a `ScErrTableNotFound`, hinting to the user the fact that replication can't continue until applications have been started at least once?

Not an optimal strategy, but simple to start with and probably quite predictable at least.

**Comment by linkdata** [comment]
Even if the log writer could be made to write to classes even if the user code isn't loaded (and I think it probably should be able to), we'd still have a race condition on first startup. And restarting the replication session is probably still the most convenient way to work around it.

**Comment by linkdata** [comment]
Btw, this should already happen - does the replicator recover from this in your setup?

**Comment by per-samuelsson** [comment]
> [...] does the replicator recover from this in your setup?

I think it does, yes. Because I only experience this error in some scenarios, and I think what is common about them is that they all run in a fresh database (where the user application has never successfully started before, and hence, classes/tables have not yet registered in metadata).

**Comment by linkdata** [comment]
I've pushed an update that will catch the 4230 and bisect the transaction with Starcounter.Metadata.ClrClass, generating a nicer `!QUIT` message listing which classes are missing. There is an inherent race condition in this, of course, as the user class may load between the transaction failing and checking the metadata tables, but it may help somewhat.

**Comment by per-samuelsson** [comment]
Sounds really good, @linkdata! I'll close this one down eventually, and we can take a new stance from where we are at this point. I'm just going to run things through once again first.

**Comment by dan31** [comment]
> @bigwad Alternatively, possibly this is related to mapping? Is the Simplified.RingX.Stuff tables handled specially and not recognized by the kernel?

Nope, no magic there.

**Comment by linkdata** [comment]
> I'm just going to run things through once again first.

@per-samuelsson: have you had time to run things through once again yet? I'd like to close this.

**Comment by per-samuelsson** [comment]
> @per-samuelsson: have you had time to run things through once again yet? I'd like to close this.

Sorry, I just forgot to close it. I've ran successful replication and haven't experienced this for quite some time, so lets close it.
