### ISSUE TITLE
Suggestions to improve maintenance of replicator

### ISSUE THREAD

**Issue by per-samuelsson** [StarcounterPrefabs/LogStreamer#18]
1. Support key ranges to be specified on the command-line with `staradmin create db`, so that you can script (re-)creation of databases.
2. Support parent IP and port to be given on the command-line of the replicator, rather than in settings. Now that I have to recreate 3 databases, I have to start replicator in each, browse to settings in each, and put in the same `locahost:1234` over and over.

Lets make each into work issues once they are destined to be done. I think [2], @linkdata has already planned for (at least moving out configuration from the database).

**Comment by linkdata** [comment]
I implemented [1] for `sccreatedb.exe` as part of writing the UI for OID ranges. I'm not sure how `staradmin create db` works though. For `sccreatedb`, use the flags `-oid` and `-lastoid`. Source that builds the command line for the UI is in `level1\src\Server\Starcounter.Server\CoreServices\DatabaseStorageService.cs`.

I expect to implement [2] this week.

**Comment by per-samuelsson** [comment]
> I implemented [1] for `sccreatedb.exe` as part of writing the UI for OID ranges.

Yeah, I knew that. Its just not surfaced in the CLI.

> I'm not sure how `staradmin create db` works though. For `sccreatedb`, use the flags `-oid` and `-lastoid`. Source that builds the command line for the UI is in `level1\src\Server\Starcounter.Server\CoreServices\DatabaseStorageService.cs`.

`staradmin` is just another management client, utilizing similar admin REST API's as the web admin, and ultimately that same code will be issued (thats the administrative server we have). My issue is to extend the stuff sent from `staradmin` and implement the actual CLI bits.

**Comment by linkdata** [comment]
Can't you just use `sccreatedb.exe`? It's in the distribution.

**Comment by per-samuelsson** [comment]
> Can't you just use `sccreatedb.exe`? It's in the distribution.

Me personally, yes I can. But is not sufficient at all for our end users, as there are plenty of other settings / higher level concepts that is out-of-scope for that tool. Creating a database involves more than that utlity provide. Hence, we have all the other stuff built on top of it.

**Comment by per-samuelsson** [comment]
On a related note, the usage message in `sccreatedb` lack mention the `-lastoid` option.

```
C:\Users\Per>screatedb
Starcounter permanent storage creation utility.
Copyright (C) Starcounter AB 2007-2016. All rights reserved.

error: No storage name specified.

usage: sccreatedb [ options ... ] name

-ip <path> Target directory.
-coll <name> Collation library to be used.
-oid <value> First record id to be used.
```

**Comment by linkdata** [comment]
For now, I will hold off on these and focus on getting filtering done and testing the core functionality.

**Comment by per-samuelsson** [comment]
> For now, I will hold off on these and focus on getting filtering done and testing the core functionality.

Yeah, thats totally the right thing to do. Thats what the OP disclaimer was about:

> Lets make each into work issues once they are destined to be done.

**Comment by linkdata** [comment]
I've added `-lastoid` to the help text of `sccreatedb.exe`, but adding support for the flags in the CLI REST API seems beyond me, I'm afraid. I've spent better part of a day now looking at the source for `staradmin`and `Starcounter.CLI`, but I can't get it to pass the parameters on to `sccreatedb.exe`. Could you do it, @per-samuelsson?

**Comment by linkdata** [comment]
The new configuration interface `ILogStreamerConfiguration` is now in place, along with a default implementation. The startup parameters have changed a bit. Running it without parameters will generate a default configuration file if none exists, or load and run if it found a configuration file.

The configuration files are per-database, and are stored in the `My Documents\Starcounter\Personal` directory with names like `myDatabase.logstreamer.xml`.

If you start with an `http:` URI, the LogStreamer will attempt to download and use the document specified as it's configuration.

If you provide a command line parameter that doesn't end in `.logstreamer.xml`, the LogStreamer will assume it is the upstream URI (parent URI) and use that when creating the default configuration file, or alter the value stored in any existing configuration file.

@per-samuelsson, I'm going to create a new issue for the `staradmin` support for `-oid` and `-lastoid` parameters, and then I'll close this issue.

**Comment by per-samuelsson** [comment]
> @per-samuelsson, I'm going to create a new issue for the staradmin support for -oid and -lastoid parameters, and then I'll close this issue.

Funny thing: the last like 30 minutes, I've started reassess the way forward for this, and I'm just about to create that issue. :smile: Give me a few more minutes.

**Comment by linkdata** [comment]
Kids these days are so slow. https://github.com/Starcounter/Starcounter/issues/3360
Closed (with a bang and a humphhh).

**Comment by per-samuelsson** [comment]
> Give me a few more minutes.

Seem you beat me to it, haha. That's fine.
