### ISSUE TITLE
Inserting instances within configured range?

### ISSUE THREAD

**Issue by per-samuelsson** [StarcounterPrefabs/LogStreamer#25]
Consider two databases, "Foo" and "Bar". "Foo" is configured with the default key range (i.e. 1-very large number). Then I configure "Bar" to have the range 1000000-1999999, and set "Bar" as a child to "Foo". 

Will an insert in "Bar" result in an error when it get applied in "Foo", even if "Foo" is more or less empty? (That is, has not reached 1000000 for sure).

**Comment by per-samuelsson** [comment]
@linkdata @bigwad

**Comment by per-samuelsson** [comment]
(Furthermore: can I be configured as a developer of LogStreamer? When it was moved, I don't have rights even to assign labels any more).

**Comment by bigwad** [comment]
No error would be raised. On top of that next Foo's object will be created with id in Bar's range thus making this cluster completely broken.

**Comment by bigwad** [comment]
No error on both the kernel and LogApplicator level. I'm not aware about safety checks in LogStreamer.

**Comment by per-samuelsson** [comment]
> No error would be raised.

Really? Hmm. I kind of hoped it would, because I have this constraint violation yet again, and the only thing that I can see could explain it would be just that... Well, ok. I guess I have to start setting up some debugging environment to track individual transactions. 

It's really really bad I can't get any info what constraint is violated. Makes it so time-consuming to find the real cause. :cry: 

> I'm not aware about safety checks in LogStreamer.

It's not the LogStreamer I'm pretty sure.

**Comment by per-samuelsson** [comment]
One thing I find weird is that one of the transactions that fail just contains a single entry, and I know for a fact there are no configured unique indexes there:

```
LogStreamer: "RPu212  TI"Sweoffshore.DataManagement.PreparedDatabase" r100000031 C"Name" "REGINA"  C"Completed" u635906163699849997  C"IsMaster" u0     ": Starcounter.ConstraintViolationException: ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8001.
   at Starcounter.Internal.DbState.InsertWithId(UInt16 tableId, UInt64 oid, UInt64& address) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Starcounter\Internal\DbState.cs:line 200
   at Starcounter.TransactionLog.LogApplicator.Apply(TransactionData transaction_data) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Server\Starcounter.TransactionLog\LogApplicator.cs:line 23
   at LogStreamer.LogStreamerSession.<>c__DisplayClass95_0.<ProcessIncomingTransaction>b__0() in C:\Users\Per\Git\SweOffshore\SweOffshoreReplicator\LogStreamerSession.cs:line 514
   at Starcounter.Db.Transact(Action action, UInt32 flags, TransactOptions opts) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Starcounter\Db.cs:line 287
   at Starcounter.Db.Advanced.Transact(TransactOptions opts, Action action) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Starcounter\Db.cs:line 233
   at LogStreamer.LogStreamerSession.ProcessIncomingTransaction(LogReadResult lrr) in C:\Users\Per\Git\SweOffshore\SweOffshoreReplicator\LogStreamerSession.cs:line 550
   at LogStreamer.LogStreamerSession.ProcessStringMessage(String message) in C:\Users\Per\Git\SweOffshore\SweOffshoreReplicator\LogStreamerSession.cs:line 572
```

The `PreparedDatabase` type is simple as this:

```cs
    [Database] public class PreparedDatabase {
        public string Name { get; set; }
        public DateTime Completed { get; set; }
        public bool IsMaster { get; set; }
    }
```

**Comment by bigwad** [comment]
Perhaps makes sense to ensure that replication partners id ranges do not overlap. It's not 100% warranty s we may have topology where two nodes are connected via some intermediate node, but anyway...

**Comment by per-samuelsson** [comment]
> Perhaps makes sense to ensure that replication partners id ranges do not overlap.

Yeah, OK. I think thats the only thing I can think of that could explain this. I'll reconfigure my cluster from scratch again, setting it up like that to see if I can get around it.

Thanks for the feedback.

**Comment by bigwad** [comment]
>I'll reconfigure my cluster from scratch again, setting it up like that to see if I can get around it.
I meant to inject this check into LogStreamer

**Comment by linkdata** [comment]
> (Furthermore: can I be configured as a developer of LogStreamer? When it was moved, I don't have rights even to assign labels any more).

Should be fixed now.

**Comment by linkdata** [comment]
I can add a check to LogStreamer that can ensure that two databases talking with each other using the LogStreamer don't have overlapping object ID ranges. It doesn't solve the issue for the global system (the LogStreamer doesn't have that information), but every little bit helps.

**Comment by per-samuelsson** [comment]
> Should be fixed now.

It is. Thanks @linkdata.

> No error would be raised.

That turns out to be a false positive. When I reconfigured the whole setup, using ranges so that "Foo" has range 1 - 99999999, and "Bar" 100000000-199999999 (i.e. no longer ranges that overlap), I don't have any conflicts any more.

**Comment by bigwad** [comment]
>It doesn't solve the issue for the global system (the LogStreamer doesn't have that information), but every little bit helps.

By the way, perhaps it's possible to any LogStreamer to build sufficient topology schema based on partial schema brought by every partners. Not global topology, but connected graph from each node's point of view. Should be enough to detect overlapped ranges.

**Comment by linkdata** [comment]
> By the way, perhaps it's possible to any LogStreamer to build sufficient topology schema based on partial schema brought by every partners. Not global topology, but connected graph from each node's point of view. Should be enough to detect overlapped ranges.

Actually, I don't think it's should even check for OID range overlap against it's peers - there are valid use cases for that (think hot-failover).

It may be appropriate to add that functionality to the application @per-samuelsson is working on. Putting it in the LogStreamer would violate the principle of [separation of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns). 

It isn't the concern of the LogStreamer to get involved in how the data streams are built globally. LogStreamer is a tool that more sophisticated applications can be built upon, just like LogStreamer builds on top of the LogReader and LogApplicator.

**Comment by linkdata** [comment]
@per-samuelsson: Are you satisfied with the answers?
@bigwad: Do you need to investigate this further?

**Comment by per-samuelsson** [comment]
> @per-samuelsson: Are you satisfied with the answers?

Well, yeah, sure. I found out how it worked myself for once, didn't I? :sunglasses:

**Comment by bigwad** [comment]
>@bigwad: Do you need to investigate this further?

Regarding this particular case - no. But I see two takeaways, may be deserving separate issues:
- inject check for object id range 
- think about how client may start replication scenario for existing database (obviously, configured by default with maximum id range). I see it's safe to reconfigure database to narrow id range, but we need some utility for this. Or we can change default configuration such that it won't occupy full id range by default, thus leaving id space for other replication partners.

**Comment by linkdata** [comment]
Very well then, closing this.
