### ISSUE TITLE
Consider further refinement of customized settings

### ISSUE THREAD

**Issue by per-samuelsson** [StarcounterPrefabs/LogStreamer#26]
Abstract: the more I consider it, the more I get the feeling that we can make forking of the log streamer into a more marginal case. I think in the majority of use cases, deploying the log streamer will need to customize just two things: "settings" (e.g. uri's to other nodes) and "table/class whitelists".

On the other side, forking and keeping up with upstream development is kind of tedious.

As a solution, and after studying the new configuration provision, I see a case where we can get away from the need for most users to fork / maintain their own copy. Just using plain configuration files is probably to simple, since table/class whitelisting will most likely need to involve code. But since the configuration now also support streaming over HTTP, we could allow users to use the log streamer "as is" and have them provide some other app that returns the configuration.

I'm currently trying to come up with a simple pattern to do this.

**Comment by per-samuelsson** [comment]
First suggestion of refinement: JSON over XML. It's there for free already (since streamer is a database app and already have neccessary references), we use it for the viewmodel in the same project, it's dominant in our other apps/libraries, etc.

And we could have this:

```json
{
  "WhiteList": [
    { "Table": "Foo", "Prio": 1 },
    { "Table": "Bar", "Prio": 2 },
  ]
}
```

and get rid of (anti-)funkyness like [StringIntPair](https://github.com/StarcounterPrefabs/LogStreamer/blob/master/StringIntPair.cs) that you are forced to when working with XML serializer.

**Comment by per-samuelsson** [comment]
Here's a relevant sample XML:

```xml
<?xml version="1.0"?>
<LogStreamerConfiguration xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <UpstreamWhitelist>
    <Key>Foo</Key>
    <Value>1</Value>
  </UpstreamWhitelist>
  <UpstreamWhitelist>
    <Key>Bar</Key>
    <Value>1</Value>
  </UpstreamWhitelist>
  <DownstreamWhitelist>
    <Key>Bar</Key>
    <Value>2</Value>
  </DownstreamWhitelist>
  <FirstUserOid>1</FirstUserOid>
  <LastUserOid>4611686018427387903</LastUserOid>
  <UpstreamUri>Tessst</UpstreamUri>
  <ReconnectMinimumWaitSeconds>1</ReconnectMinimumWaitSeconds>
  <ReconnectMaximumWaitSeconds>86400</ReconnectMaximumWaitSeconds>
</LogStreamerConfiguration>
```

**Comment by per-samuelsson** [comment]
> First suggestion of refinement: JSON over XML.

Think I've found a way to do rather minimal surgery and support both. I'll open up a separate issue for that and assign it to me.

**Comment by linkdata** [comment]
Yeah, the XML serializer really hates Dictionary types. I chose it over JSON simply to avoid introducing an external dependency on Newtonsoft's Json library.

**Comment by per-samuelsson** [comment]
> I chose it over JSON simply to avoid introducing an external dependency on Newtonsoft's Json library.

And you wound't have needed this, as I wrote earlier:

> [...] since streamer is a database app and already have neccessary references

Everything needed in terms of serializing/deserializing is already in effect in the log streamer project, just that it's used for the viewmodels. I quite recently was given some time to learn that stuff myself, and it's quite blazing actually. I'll fill you in eventually.

**Comment by per-samuelsson** [comment]
I don't see anything more that need to be done at this point, now that I've completed #27.
