### ISSUE TITLE
Add support for JSON configuration

### ISSUE THREAD

**Issue by per-samuelsson** [StarcounterPrefabs/LogStreamer#27]
Background in #26.

I'll make an initial attempt to support JSON and XML in parallel. I've already spiked it, looks like I can make it pretty cheap. Will begin only support JSON over HTTP (so file config still remain XML-only).

Let me know you don't have any objections @linkdata, and I'll bring it on.

**Comment by linkdata** [comment]
Sure, just be aware that it's still a moving target. Especially the whitelist duality due to XmlSerializer not being able to handle Dictionary types.

**Comment by per-samuelsson** [comment]
> Especially the whitelist duality due to XmlSerializer not being able to handle Dictionary types.

Yeah, sure. The idea I have involves basically no redesign of what is exposed already. It basically only extends it by acknowledging JSON when reaching out for config, and provides a super trivial adapter that expose such result as configuration type the log streamer already can work with. Future refactoring should be very straightforward.

**Comment by per-samuelsson** [comment]
I'm changing the pattern the log streamer use to identify a config argument, looking instead for `*logstreamer.config.*`. This allows us to support `logstreamer.config.xml` and `logstreamer.config.json`.

I'm still not changing the default from XML though, so things will work as they used to, if you just rename any existing config like that.

**Comment by per-samuelsson** [comment]
Pushelipushed in https://github.com/StarcounterPrefabs/LogStreamer/commit/8f8ed464db0316ab0523e22219d6a74d460a5416.

The log streamer now support file- and REST-based XML configuration, and additional REST-based JSON configuration. 

Pseudo-code to provide the log streamer with JSON configuration from a HTTP server:

```cs
Handle.GET("my/custom/logstreamer.config.json", () => {
  var config = "{ "UpstreamUri": "my.upstreamnode.com:1234" }";
  return new Response() {
    ContentType = "application/json",
    StatusCode = 200,
    Body = config
  }
});
```

With the above running under `my.childnode.com:80`, start the streamer like so for it to be consumed:

```cmd
star logstreamer.exe http://my.childnode.com:80/my/custom/logstreamer.config.json
```
