### ISSUE TITLE
Make JSON the configuration of LogStreamer (drop XML)

### ISSUE THREAD

**Issue by per-samuelsson** [StarcounterPrefabs/LogStreamer#28]

**Comment by per-samuelsson** [comment]
I've cleared this with @linkdata.

**Comment by per-samuelsson** [comment]
@linkdata 

When doing this, I'm dropping the feature that the log streamer creates a default configuration as a file on disk when either no configuration is given, or a vale is given and that is invalid. Especially that last case I think is wrong, or at least overkill.

Personally, I don't feel we need that feature at all. And if you disagree, I suggest we implement it as a "tooling thing", keeping them separate. As an example, supporting some way to instruct the log streamer to generate a default config, like `logstreamer new config`.

**Comment by per-samuelsson** [comment]
Also removing that feature that if you provide an upstream URI on the command line, and the configuration is file based, the file based configuration is updated. Touching FPS in my book. :smile: 

You are to kind, @linkdata. Just tell users what to pass, and make them pass that. And if the don't, punish them. :wink:

**Comment by per-samuelsson** [comment]
@linkdata 

You're not using the partials and wwwroot stuff anymore, right? The HTML provision is now solely based on what is provided by the streamer entrypoint class, correct? 

If so, I won't bother to adapt those, but instead just drop them while I'm at it.

**Comment by per-samuelsson** [comment]
@linkdata 

I'm about to wrap this one up soon, based on decisions on what I like (you gave me that freedom, right? :smile:). It's messing quite a bit with some central pieces - e.g. project file and Program.cs - so please don't do any major changes to those until I've pushed it.

**Comment by linkdata** [comment]
Råger, Vilko. And on the wwwroot stuff, nuke it from orbit. It's the only way to be sure.

**Comment by linkdata** [comment]
So what is now the easiest way to make persistent configuration changes to a LogStreamer running on a certain database?

**Comment by per-samuelsson** [comment]
Shared to the world in https://github.com/StarcounterPrefabs/LogStreamer/commit/974511a37acd567b1de952e197c1998bc1769bfd.

Before you pull, here's a writeup of all stuff that has happened:

1. XML configuration no longer supported (duh).
2. Everything file-related is now opaque to the logstreamer - if you pass it a config URI that is file based, it will read that file as a JSON config. No more, no less.
3. LogStreamerConfiguration now provision (static) configuration defaults + a `Load` method that
returns an abstraction, not an implementation.
4. You can pass the log streamer a config URI and a upstreamURI, just as before. See how they are treated below.
5. The root page now show when there are whitelisted tables, and you can click the set to see a page with the different sets.
6. Older viewmodels and views are dropped
7. New handler exposed: `/logstreamer/default.config.json`. Does what the URI implies.
8. The `Program.Whitelist` is removed in favor of new handler ´/logstreamer/sample.config.json`. Invoke that one to see samples in JSON format. It's randomized, just like `Program.Whitelist`, so hit F5 in the browser a few times to see different variations.

Q: I want to start with a default configuration from file?
A: Browse to `/logstreamer/default.config.json`. Copy the content, save it to a file with `config.json` ending and pass the path along to the log streamer upon next start.

Q: What happens if I don't pass any configuration URI?
A: The log streamer will internally fetch defaults from [7].

Q: What happens if I pass a config URI **and** an upstream URI?
A: The log streamer will override the UpstreamUri resolved from config with the explicit one you give.

Q: What happens if I pass **only** an upstream URI?
A: Q1 + Q2.

**Comment by per-samuelsson** [comment]
> So what is now the easiest way to make persistent configuration changes to a LogStreamer running on a certain database?

I knew I should have written the above *before* I pushed it - you're always so het på gröten dammit!

**Comment by per-samuelsson** [comment]
> So what is now the easiest way to make persistent configuration changes to a LogStreamer running on a certain database?

Hm, I realized that particular question was not answered. The answer is: you don't. We gather configuration at startup, you need to change that - go edit and restart. You think thats awful, I can support a REST PUT (or POST) to get it done.

**Comment by linkdata** [comment]
Slow kid is slow.

What? You expect me to just sit around and do nothing while you compose intelligent posts? No, the best way to find out how high a cliff is, is to jump off and count the seconds loudly before you smack face first into the ground.

I will tweak it a bit to look for a `..\Starcounter\Personal\DBNAME.logstreamer.config.json` before grabbing the `/logstreamer/default.config.json` result body.

**Comment by per-samuelsson** [comment]
> I will tweak it a bit to look for a `..\Starcounter\Personal\DBNAME.logstreamer.config.json` before grabbing the `/logstreamer/default.config.json` result body.

Yeah, sure, do. Sounds good.

Closing this one as "done". Open up a new issue in case you think something is missing, wrecked, w/e.
