### ISSUE TITLE
Help specifying upstream URI

### ISSUE THREAD

**Issue by per-samuelsson** [StarcounterPrefabs/LogStreamer#29]
I'm using the JSON configuration, and the active URI I return is `ws://localhost:8085`. That gives me this:

> ws://localhost:8085/: "Unable to connect to the remote server": Reconnect at 18-Feb-16 4:05:19 PM

Before that, I returned only `localhost:8085`, but that raised an error saying I must prefix it with either `ws://` or `wss://`.

@linkdata, any idea?

**Comment by per-samuelsson** [comment]
OK, after I changed to return this:

```
ws://localhost:8085/LogStreamer/service
```

I seem to get pass the above error at least. But I guess thats not what we want log streamer configuration to require?

Now I have this:

> ws://localhost:8085/LogStreamer/service: "System.AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.SEHException: External component has thrown an exception.   at Starcounter.TransactionLog.LogReaderImports.TransactionLogMoveNext_imp(IntPtr log_handle)   at Starcounter.TransactionLog.LogReaderImports.TransactionLogMoveNext(IntPtr log_handle) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Server\Starcounter.TransactionLog\LogReaderImports.cs:line 46   at Starcounter.TransactionLog.LogReader.<read_next_transaction>d__5.MoveNext() in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Server\Starcounter.TransactionLog\LogReader.cs:line 48--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()   at LogStreamer.FilteredLogReader.<ReadAsync>d__16.MoveNext() in C:\Users\Per\Git\StarcounterPrefabs\LogStreamer\FilteredLogReader.cs:line 268--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at LogStreamer.LogStreamerSession.<ReadAsync>d__106.MoveNext() in C:\Users\Per\Git\StarcounterPrefabs\LogStreamer\LogStreamerSession.cs:line 420   --- End of inner exception stack trace ------> (Inner Exception #0) System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.   at Starcounter.TransactionLog.LogReaderImports.TransactionLogMoveNext_imp(IntPtr log_handle)   at Starcounter.TransactionLog.LogReaderImports.TransactionLogMoveNext(IntPtr log_handle) in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Server\Starcounter.TransactionLog\LogReaderImports.cs:line 46   at Starcounter.TransactionLog.LogReader.<read_next_transaction>d__5.MoveNext() in C:\Users\Per\Git\Starcounter\PNext\Level1\src\Server\Starcounter.TransactionLog\LogReader.cs:line 48--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()   at LogStreamer.FilteredLogReader.<ReadAsync>d__16.MoveNext() in C:\Users\Per\Git\StarcounterPrefabs\LogStreamer\FilteredLogReader.cs:line 268--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at LogStreamer.LogStreamerSession.<ReadAsync>d__106.MoveNext() in C:\Users\Per\Git\StarcounterPrefabs\LogStreamer\LogStreamerSession.cs:line 420<---": Reconnect at 18-Feb-16 4:15:25 PM

Not to sure what to make of that? @bigwad? @linkdata?

I pulled the log reader sources just recently, but I think I haven't pulled Starcounter sources in like a few days. Maybe they are not in sync or something? I'll try to make sure I have a crisp environment to see if I can get pass it.

**Comment by linkdata** [comment]
I have no clue on the exception. On the URI, yes, we want a complete URI that goes to the LogStreamer websocket service point. So it should indeed look like "ws://localhost:8085/LogStreamer/service" before using it. I did have that CleanUpstreamUri() function to allow people to use shorter forms for convenience, not sure if you nuked it or not.

**Comment by per-samuelsson** [comment]
> I did have that CleanUpstreamUri() function to allow people to use shorter forms for convenience, not sure if you nuked it or not.

I kept it for upstreams provided on the command-line, allowing a convenient way to run the log streamer with default configuration like this: `logstreamer my.upstream.com:123`

**Comment by linkdata** [comment]
The current version now has auto-cleaning of the upstream URI in all cases where it's missing scheme and auth markers (the `://` bits in the URI). So it will once again accept convenience strings in the form `host:port` and decorate as necessary.

Regarding the exception, I still don't know. It looks to me like it's in `logreader.dll` (since it crashes in `Starcounter.TransactionLog.LogReaderImports.TransactionLogMoveNext_imp(IntPtr log_handle)`).

@bigwad, what do you think?

**Comment by per-samuelsson** [comment]
FWIW, I didn't experience this any time after I reported it as far as I recall, so if @bigwad doesn't have anything he'd like to add or somehow take this issue on, it's fine by me we close it as a wontfix.

**Comment by bigwad** [comment]
Can't get much from what we have here. Please, close as I don't have the rights.
