### ISSUE TITLE
Failed robustness test with !READY / !QUIT Starcounter.TransactionLog.TransactionLogException: Exception 

### ISSUE THREAD

**Issue by dan31** [StarcounterPrefabs/LogStreamer#32]
I was running the LogStreamer with LogStreamerBulker (https://github.com/StarcounterSamples/LogStreamerBulker) on a real production environment. The vessel travels between Germany shore and a power farm on a sea island. For several days the vessel encountered some short disconnection periods on a satellite, which the LogStreamer survived. After several days of run, Windows on a Ground decided to update itself and the machine has automatically restarted. This resulted in a day of disconnection of a vessel from a ground.

After that, I tried to restore the running state and failed. When trying to connect with a LogStreamer from the Vessel, we have this repetitive output on a Ground:

```3/10/2016 9:59:17 AM	78430bbb-762e-43fd-9993-75516ae60c13	DEFAULT	WsSendCmd	!TPOS "" u2436538
3/10/2016 9:59:17 AM	78430bbb-762e-43fd-9993-75516ae60c13	DEFAULT	WsSendCmd	!READY
3/10/2016 9:59:17 AM	78430bbb-762e-43fd-9993-75516ae60c13	DEFAULT	WsRecvCmd	!TPOS "" u2436533
3/10/2016 9:59:17 AM	78430bbb-762e-43fd-9993-75516ae60c13	DEFAULT	WsRecvCmd	!READY
3/10/2016 9:59:17 AM	78430bbb-762e-43fd-9993-75516ae60c13	DEFAULT	WsSendCmd	!QUIT Starcounter.TransactionLog.TransactionLogException: Exception of type 'Starcounter.TransactionLog.TransactionLogException' was thrown. at Starcounter.TransactionLog.LogManager.OpenLog(String db_name, String log_dir, LogPosition position) in C:\TeamCity\TeamCity9\buildAgent\work\sc-74\Level1\src\Server\Starcounter.TransactionLog\LogManager.cs:line 18 at LogStreamer.FilteredLogReader..ctor(LogStreamerSession logStreamer, Dictionary`2 tablePos, HashSet`1 tableFilter) in C:\Starcounter\LogStreamer-master\FilteredLogReader.cs:line 77 at LogStreamer.LogStreamerSession.InitializeReader(Int32 index) in C:\Starcounter\LogStreamer-master\LogStreamerSession.cs:line 445 at LogStreamer.LogStreamerSession.StartStreaming() in C:\Starcounter\LogStreamer-master\LogStreamerSession.cs:line 469 at LogStreamer.LogStreamerSession.ProcessStringMessage(String message) in C:\Starcounter\LogStreamer-master\LogStreamerSession.cs:line 748```

Hence, replication is unable to continue and the production environment is in non-functional state. Just in case, I specifically emphasize there: it would be false to assume that in a day replica should be considered dead. There is no 100% replica in general: data is streamed in 2 directions, from master to replica and vice versa. Hence, the full recreation of a data ("initialaise an empty replica") should only be a goodwill of a person's action, available via CLI or GUI, not some automatic decision making by us. I mention it here, since I recall a discussion regarding when the replica should be recreated, and I thought then that a day of disconnection might be a reason for that current malfunction. It would be a big mistake to voluntary take a decision to re-create a replicas data in some condition, hence destroying the whole setup for the customer or making it non-functional.

The purpose of the robustness test is to prove that the Vessel and Ground LogStreaming can run autonomously in many different real conditions without data loss, running state corruption and a necessity of a manual hand-held administration of instances. We do not ship a special person to administrate the instances daily, instead we must build systems which are self-sufficient to the most possible extent, thus any situation should be handled robustly. In the current condition, I couldn't recover the state by hand as well.

__Steps to reproduce__

All necessary data is located here:
https://www.dropbox.com/sh/lmkcy1l7afygrg3/AADWk_2BduwrO730pntH7NR9a?dl=0
Starcounter Version 2.3.941 pnext
Apps run are: LogStreamer and LogStreamerBulker
I attach the compiled versions of these apps and put them on ```C:\TestLS```.
Before running the apps, I create the empty databases named "default":
on Vessel with a range:  700000000000001 - 1400000000000000
on Ground with a range: 1 - 700000000000000
Then I substitute the ```default``` database data with the data from archives ```Vessel.7z``` and ```Ground.7z``` correspondingly. I only substitute the actual data images and logs, but not the conf files.

On a Vessel I run:
```
C:\TestLS>star LogStreamerBulker.exe
LogStreamerBulker -> default (started, default port 8080, admin 8181)
Starting LogStreamerBulker in DEFAULT with 'origin' = 'vessel/default'

C:\TestLS>star LogStreamer.exe ws://159.253.26.15:8080/LogStreamer/service
LogStreamer -> default (started, default port 8080, admin 8181)
Starting LogStreamer in DEFAULT, OID range 700000000000001 - 1400000000000000. U
pstreamUri: 'ws://159.253.26.15:8080/LogStreamer/service'.
```
On a Ground I run:
```
C:\TestLS>star LogStreamerBulker.exe
LogStreamerBulker -> default (started, default port 8080, admin 8181)
Starting LogStreamerBulker in DEFAULT with 'origin' = 'ground/default'

C:\TestLS>star LogStreamer.exe @enabled
LogStreamer -> default (started, default port 8080, admin 8181)
Starting LogStreamer in DEFAULT, OID range 1 - 700000000000000. UpstreamUri: ''.
```
When all run, I activate a connection on a Vessel side from a GUI: http://127.0.0.1:8080/LogStreamer.

@bigwad please investinage. The priority for an issue is high. CC @linkdata

**Comment by bigwad** [comment]
The issue is too aggressive log retention. Will fix it today or at least tomorrow.
In current product state, this is unrecoverable. LogStreamer can't start over if position is lost.

**Comment by linkdata** [comment]
> The issue is too aggressive log retention. Will fix it today or at least tomorrow.

Well, we need to be able to support quite a lot of retained logs. At least a month, preferably limited only by available space. What do you propose to limit it to?

> In current product state, this is unrecoverable. LogStreamer can't start over if position is lost.

Why would it be unrecoverable? And what do you mean by "Position is lost"? Please clarify.

**Comment by bigwad** [comment]
>Well, we need to be able to support quite a lot of retained logs. At least a month, preferably limited only by available space. What do you propose to limit it to?

As to this specific problem, it's not about the limits. I designed retention in the way that keeps only latest optimized log file. It's enough for database reload, but not for log reader. Effectively log reader restores database at particular point of time, so it needs optimized log for that point of time as well.

>Why would it be unrecoverable? And what do you mean by "Position is lost"? Please clarify.

Regardless what retention limit we choose, finally it will be reached and some logs get removed (thus some position become lost). We don't have any recovery plan for such scenario. Neither automatic nor manual.

**Comment by linkdata** [comment]
So what you're saying is that the position LogStreamer is trying to start from is no longer available in the logs?

So when you said "too aggressive log retention", what you really meant was "too aggressive log removal"? Because they mean opposite things.

**Comment by dan31** [comment]
Great! Then I understand what happened. On a side notes, @bigwad we'll need to have the log retention documented at some moment when its function is well established. Currently, as I understand, its defaults are in progress of establishing. Also, be assured from me that for any unexpected situations like this restart my intended watchdog is supposed to recover the instance. So, one day because of Windows update won't be an issue, but one day because of the vessel travelling in Bermudas still might be a case... :)

Maybe, for this recovery procedure, some old logfiles must be restored from their retention folder prior to running the instance back, or something like this? It depends on how you will shape it, of course.

I can also say that disk space isn't an issue on these particular machines. This will become less an issue as well when the 256-mb logfiles will reduce to lesser format.

**Comment by bigwad** [comment]
Yes, too many optimized log files was removed in this case. That is design flaw, not matter of limits.

By "log retention" I mean well-known term. "Too relaxed log retention" sounds contradictory.
Hope, no more misunderstanding on this.

**Comment by linkdata** [comment]
Thanks for clearing that up. 

> "Too relaxed log retention" sounds contradictory.

Indeed it does. I think the phrase you were looking for was "insufficient log retention".

While we're at this, could we get a more descriptive message for this condition? When it happens in the future, seeing something like "required log file missing" in the exception text would help users a lot.

**Comment by bigwad** [comment]
Fixed. Should be available in upcoming nightly.
