### ISSUE TITLE
What means `magic` and why this word was used as a name?

### ISSUE THREAD

**Issue by miyconst** [StarcounterPrefabs/LogStreamer#38]

**Comment by linkdata** [comment]
https://en.wikipedia.org/wiki/Magic_number_(programming)

They're enumerations with constants identifying things. It's a bad habit to call them magic numbers. In this case, doubly so since there are two different enumerations, both with the name Magic. I'll rename it to something more sensible.

**Comment by miyconst** [comment]
Thanks for the explanation. No need to rename. I will do that myself, since I am doing a refactor and new features in my branch. Once I am done there, I will merge it to master.
